/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebtRouteImport } from './routes/debt'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtRoute = DebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debt': typeof DebtRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debt': typeof DebtRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debt': typeof DebtRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/budgets'
    | '/contact'
    | '/dashboard'
    | '/debt'
    | '/forgot-password'
    | '/goals'
    | '/health'
    | '/help'
    | '/insights'
    | '/investments'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/transactions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/budgets'
    | '/contact'
    | '/dashboard'
    | '/debt'
    | '/forgot-password'
    | '/goals'
    | '/health'
    | '/help'
    | '/insights'
    | '/investments'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/transactions'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/budgets'
    | '/contact'
    | '/dashboard'
    | '/debt'
    | '/forgot-password'
    | '/goals'
    | '/health'
    | '/help'
    | '/insights'
    | '/investments'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/transactions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DebtRoute: typeof DebtRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt': {
      id: '/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof DebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DebtRoute: DebtRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
